version: '3'

services:
  backend:
    image: birds7/timback
    environment:
      STUDENT_ID: "A01229374"
      STUDENT_NAME: "xavier"
      

  nginx:
    image: birds7/timfront
    environment:
      API_URL: backend
      API_PORT: 5000
    # env_file:
    #   - variables.env
    ports:
      - 5000:80

